DELETE FROM AUTHS;
DELETE FROM AUTH_NAMES;

-- 권한 종류
insert into AUTH_NAMES 
(UNIQUE_ID,AUTH_NAME)
values
('ROLE_MANAGER','SYSTEM_MANAGER'),
('ROLE_ADMIN','ADMIN'),
('ROLE_USER','USER'),
('ROLE_GUEST','GUEST')
;